apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "payment-api.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
